development:
  adapter: mysql
  database: crm2
  username: root
  password: 12077752
  host: localhost


test:
  adapter: mysql
  database: crm2
  username: root
  password: 12077752
  host: localhost


production:
  adapter: mysql
  database: crm2
  username: root
  password: 12077752
  host: localhost

