--- 
Anulacion de ODT: !map:HashWithIndifferentAccess 
  "0": ax005
  "1": ax005
  "2": ax005
  "3": ax005
  "4": ao002
Modificacion de Monto: !map:HashWithIndifferentAccess 
  "0": aq019
  "1": aq017
  "2": aq017
  "3": aq017
  "4": mm000
Eliminar Oportunidad: !map:HashWithIndifferentAccess 
  "0": am013
  "1": am013
  "2": am013
  "3": am013
  "4": delo01
Crear Orden Interna: !map:HashWithIndifferentAccess 
  "2": al012
  "3": al012
  "4": coi111
  "0": al012
  "1": al012
Cambiar Empresa o Tipo: !map:HashWithIndifferentAccess 
  "4": ce0001
  "0": af100
  "1": af006
  "2": af006
  "3": af006
Fecha de Entrega (Ej): !map:HashWithIndifferentAccess 
  "2": ao015
  "3": ao015
  "4": fe1110
  "0": ao015
  "1": ao015
Fecha de Entrega (Op): !map:HashWithIndifferentAccess 
  "0": ap016
  "1": ap016
  "2": ap016
  "3": ap016
  "4": fe111
Cargo Facturas - Facturacion: !map:HashWithIndifferentAccess 
  "0": aj010
  "1": aj010
  "2": aj010
  "3": aj010
  "4": cff1011
Factura en Blanco: !map:HashWithIndifferentAccess 
  "0": an014
  "1": an014
  "2": an014
  "3": an014
  "4": fw001
Anular Guia de Remision: !map:HashWithIndifferentAccess 
  "3": ad004
  "4": ag002
  "0": ad004
  "1": ad004
  "2": ad004
ODT en Standby: !map:HashWithIndifferentAccess 
  "0": ap035
  "1": ar035
  "2": di035
  "3": es035
  "4": osb001
Anulacion de Factura: !map:HashWithIndifferentAccess 
  "0": aa001
  "1": aa001
  "2": aa001
  "3": aa001
  "4": af0002
Cambio de Precio de ODT Facturada (Facturacion): !map:HashWithIndifferentAccess 
  "0": ah008
  "1": ah008
  "2": ah008
  "3": ah008
  "4": cpf0010
Cambio de Precio de ODT Facturada (Comercial): !map:HashWithIndifferentAccess 
  "0": ag007
  "1": ag007
  "2": ag007
  "3": ag007
  "4": cpc1001
Anulacion de Nota de Credito: !map:HashWithIndifferentAccess 
  "0": ab002
  "1": ab002
  "2": ab002
  "3": ab002
  "4": an002
Cargo Facturas - Cobranza: !map:HashWithIndifferentAccess 
  "0": ai009
  "1": ai009
  "2": ai009
  "3": ai009
  "4": cfc1111
Autorizacion Consorcio: !map:HashWithIndifferentAccess 
  "0": ae005
  "1": ae005
  "2": ae005
  "3": ae005
  "4": aut002
Crear Garantia/Reclamo: !map:HashWithIndifferentAccess 
  "0": ak011
  "1": ak011
  "2": ak011
  "3": ak011
  "4": cg0001
