# Converts dates
# Adds a final ";" to each INSERT generated by mdb-export

STDIN.readlines.each do |l|
  l.gsub!(/'([0-9]{2})\/([0-9]{2})\/([0-9]{2}) ([0-9]{2}:[0-9]{2}:[0-9]{2})'/, "'20\\3/\\1/\\2 \\4'")
  puts l.strip + ";"
end

